### PR TITLE
Prevent default on search enter. Fixes #21

### LINKED ISSUE #21: App crashing on searching 'Notable'
Hi,

Using Notable.1.0.1.exe on Window 7 64 bit. After opening an app I wrote 'Notable' in search bar and pressed enter, after that an error occured with log as below:

`Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Error (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:13:314)
    at ca (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at t (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:118:40)
    at af (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:150:11)
    at fg (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:154:21)
    at Q (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:468)
    at Ag (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)`

### PR DESCRIPTION
**Pull request by James-Quigley**

### CODE REVIEW

**Comment by James-Quigley** [comment]
Happy to change that up. Should I just make it a div? Unsure of if any of the css classes used are reliant upon this being a form

**Comment by James-Quigley** [comment]
Happy to change that up. Should I just make it a div? Unsure of if any of the css classes used are reliant upon this being a form

**Comment by fabiospampinato** [comment]
> Should I just make it a div? 

Yes please. It looks like this line should be updated too: https://github.com/fabiospampinato/notable/blob/master/src/renderer/template/misc.css/#L94-L95. There's currently an issue with rebuilding the CSS (#41) so I guess either do the change and I'll test it or I'll do it myself when I can, hopefully tomorrow.

**Comment by fabiospampinato** [comment]
Sorry if I'm not merging this but it was quicker this way rather than telling you to remove that unnecessary onSubmit handler.

**Pull request closed without merging**
