### PR TITLE
fix issuse  #199,  #235 of not render correctly

### PR DESCRIPTION
**Pull request by lianghongzhuo**
These issues are caused by showdown-katex, this package set `~ ~` as a math equation.
By comment, the `~ ~` delimiters at [this line](https://github.com/lianghongzhuo/showdown-katex-studdown/blob/master/src/showdown-katex.js#L49) the bug will solve. 
I think most people are using delimiters like `$$` or `$` to write LaTex code, so this change will have no harm.

### CODE REVIEW

**Comment by bendem** [comment]
Does that mean there is no option to render asciimath anymore? Also, what happens if I include `$$` in a code block, does the problem still happen (I can think of a few languages where a variable starting with `$$` works)?

**Comment by lianghongzhuo** [comment]
@bendem 
First question: according to [this line](https://github.com/fabiospampinato/notable/blob/8fff464777b691544173275b5ac4bfd34e048bd1/src/common/config.ts#L51) the asciimath supposed to supported by using `&&  &&`.
But when I test a asciimath it not work in the version 1.1.0 release.
both `~ ~`, ` &&  &&` does not render correctly. (this might be another issuse)
Here is a example:
```
&&sum_{i=1}^n i^3=((n(n+1))/2)^2&&
~sum_{i=1}^n i^3=((n(n+1))/2)^2~
```

For the second question, code block with `$$ $$` in side does not have any render problems.

**Comment by lianghongzhuo** [comment]
shot

**Comment by fabiospampinato** [comment]
@lianghongzhuo I think there are multiple problems with our usage of KaTeX right now:

- Non math expressions are evaluated as math expressions #199 #235 (perhaps we could detect this?)
- I think ASCIIMath isn't working everywhere where it's supposed to
- There appear to be some rendering errors #255
- Maybe only $$..$$ and $..$ should be supported, both of them should support ASCIIMath also

Would you like to take care of (some of) these issues? I'm probably going to publish another update later today or tomorrow and I'd like to properly fix KaTeX in the next iteration.

**Comment by lianghongzhuo** [comment]
@fabiospampinato  Yes, I can take a deep look at it at weekend.

**Comment by fabiospampinato** [comment]
@lianghongzhuo actually I think I have an idea on how to fix this and similar issues, I'm going to implement those next, then I'm probably going to publish v1.3. If then there are still problems feel free to open an issue about that.

**Pull request closed without merging**
