### PR TITLE
Use markdown tables for Comparison table to reduce amount of scrolling

### PR DESCRIPTION
**Pull request by xfix**

### CODE REVIEW

**Comment by mvasilkov** [comment]
Came here to offer literally the same edit. 😀

**Comment by fabiospampinato** [comment]
Thanks for the PR but I don't think this is the right direction. We really need a scrollable table in order for it to be readable. Currently if you switch to a plain Markdown table it would barely be readable, if we add a few more apps to the table (like OneNote or Typora) it would become totally unreadable.

Rather there should be a script that renders the table into an image that I can link to into the readme.

**Comment by xfix** [comment]
It is scrollable, but sure.

screenshot_20181227_211341

**Comment by fabiospampinato** [comment]
@xfix Oh, actually I didn't realize it was scrollable 🤔 That may make the table more readable than it currently is, but still not very readable IMHO, I think the best option is to render the table into an image, if anyone would like to help with that I'll appreciate it.

**Comment by johnletey** [comment]
> I think the best option is to render the table into an image, if anyone would like to help with that I'll appreciate it.

I could try to write a Python script that outputs an image given the table in CSV form (then we could have a CI that can regenerate the image any time someone changes the CSV in a commit ... the CI could also have automated tests, as proposed in #68).

**Pull request closed without merging**
