### PR TITLE
Add .vscode to .gitignore

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Hi, I think we should make git ignore `.vs-code`!
(https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations)

### CODE REVIEW

**Comment by fabiospampinato** [comment]
@sosukesuzuki you mean `.vscode` without the hyphen?

**Comment by sosukesuzuki** [comment]
@fabiospampinato Sorry..., I was wrong. I'll fix it.

**Comment by svenefftinge** [comment]
Why would you want to exclude it? 
The workspace settings are meant to be shared in the team.
User specific settings go into the user home and are not shared.

**Comment by sosukesuzuki** [comment]
Sharing `.vscode` is related only VSCode users. So, I thought we should ignore it. However if you(contributors) need it, I agree with that you commit the appropriate `.vscode`.

**Comment by fabiospampinato** [comment]
I don't think we are going to add vscode-specific settings at the repo level, so we might as well ignore `.vscode`.

@sosukesuzuki do you need to add vscode-specific settings to your fork or something though?

**Comment by sosukesuzuki** [comment]
@fabiospampinato I don't need to add `.vscode` at least now. 
However, I think it is good to remove `.vscode` from `.gitignore` when it becomes necessary.

**Comment by fabiospampinato** [comment]
Thank you @sosukesuzuki !

**Pull request merged**
