### PR TITLE
Export: add export to html

### PR DESCRIPTION
**Pull request by mnikn**
Quick Implement of [#14](https://github.com/fabiospampinato/notable/issues/14), right now just support export to html, but I think if we need to export to pdf or any other datatype, pandoc or anything can do the convert stuff would be better.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
@mnikn can you add a submenu to "Export..." with currently "HTML" as the only entry? Also can you adhere more to my coding style?

**Comment by fabiospampinato** [comment]
Thanks! I'm going to change it a bit though, as I really wanted a submenu under "Export...", and the implementation could perhaps be a bit better, the "cwd" container has nothing to do with exporting, we should probably add a whole new "export" container.

**Comment by fabiospampinato** [comment]
We should also support multi-note exporting.

**Comment by fabiospampinato** [comment]
There should also be a switch for exporting attachments.

**Comment by mnikn** [comment]
Sounds nice, a new "export" container will cost more efforts but also more powerful.

**Pull request merged**
